Repository viatsko/awesome-vscode, pull requests merged in 2018-10, with the labels that each got.

#186 Add Terraform to Lint list
  README.md
Labels: Linting & Intellisense, New Extension

#182 Add vscode-carbon.now.sh to the list
  README.md
Labels: New Extension

#164 Included ES7 React/Redux/GraphQL/React-Native snippets under Productivity
  README.md
Labels: New Extension

#195 Add duplicate action package
  README.md
Labels: New Extension

#193 Add Base16 Ocean Dark Extended theme
  README.md
  themes/screenshots/kleber-swf.ocean-dark-extended.png
Labels: New Extension, Themes

#175 Add Befunge to syntax list
  README.md
Labels: New Extension, Syntax

#151 Adding highlight-matching-tag to the list
  README.md
Labels: New Extension

#200 Slime Theme by smlombardi
  README.md
  themes/screenshots/slime.png
Labels: Themes

#179 Add SmoothType extension
  README.md
Labels: New Extension

#194 Add SVG language extension
  README.md
Labels: New Extension

#197 Add Monokai Pro Theme and Fix Checkboxes in PR Template
  PULL_REQUEST_TEMPLATE.md
  README.md
  themes/screenshots/1079cc76.png
Labels: New Extension, Themes

#209 Add Markdown all in one
  README.md
Labels: New Extension

#214 Add Bash Debug
  README.md
Labels: New Extension
